### ISSUE TITLE
Error: Slack request failed with error not_allowed_token_type

### ISSUE THREAD

**Issue by max-winderbaum** [jackellenberger/emojme#27]
I'm trying to use `emojme.add` but I keep hitting the error on this line: https://github.com/jackellenberger/emojme/blob/master/lib/emoji-admin-list.js#L55

The error given is `not_allowed_token_type` but I'm definitely using a user token - I regenerated one and it's working to make requests for `emoji.list`

Do we really need to get `adminList`? Do I have to be an admin to use this tool?

**Comment by max-winderbaum** [comment]
Update: I was able (I think) to get around it with [this commit](https://github.com/max-winderbaum/emojme/commit/53d22287166b0d33a19b59f20436d628ca6ebea6) but now I'm getting the `not_allowed_token_type` error for the `emoji.add` endpoint [here](https://github.com/max-winderbaum/emojme/blob/53d22287166b0d33a19b59f20436d628ca6ebea6/lib/emoji-add.js#L25)

**Comment by jackellenberger** [comment]
Hey @max-winderbaum, I'm guessing you are using a bot or workspace token, but this library only works with [user tokens](https://api.slack.com/docs/token-types#user). You can see how to get one [in the readme](https://github.com/jackellenberger/emojme#finding-a-slack-token)

It's pretty unclear though that that's the case, so I'll leave this open until I update the readme to put that info up front.

**Comment by jackellenberger** [comment]
As to why you need a user token and why I use adminList - it's exactly for this issue. `emoji.list` lets you download emoji, but you can't do anything else emoji-related with that kind of low auth token.

Also, I'm expecting `emoji.list` to change very soon and become paginated as well, I thought i'd just skip that issue when it comes up and get the whole adminList, which also gives the slack instance, original user, and 🤞 one day, upload date.

**Comment by max-winderbaum** [comment]
@jackellenberger Thanks for your fast response! I'm getting my user token from this url: https://api.slack.com/custom-integrations/legacy-tokens

Should I be getting it elsewhere? Is that not the token I want?

**Comment by max-winderbaum** [comment]
Nevermind - I missed the part you pointed me to in the README! I'll try that now.

**Comment by jackellenberger** [comment]
Correct, emojis are locked down to _only_ be intractable by users. User tokens honestly aren't meant to be thrown in to a cli app or module, but 🤷‍♀️ I don't feel too bad about abusing them if Slack won't give us a better way. User tokens are (for now) embedded in the html of any logged-in slack instance, so you can get them from `/messages` or `/customize`, or most other places.
