### ISSUE TITLE
Instructions for grabbing token no longer work

### ISSUE THREAD

**Issue by curtisgibby** [jackellenberger/emojme#44]
It appears that Slack changed something on their side that prevents the current method for determining an API token from working.

The readme says: 
> It's easy! Open any signed in slack window, e.g. subdomain.slack.com/messages, right click anywhere > inspect element. Open the console and paste:
> ```
> window.prompt("your api token is: ", window.boot_data.api_token)
> ```

As of now, the console throws an error:

```
TypeError: window.boot_data is undefined
```

Any other ways of finding the API token?

**Comment by jackellenberger** [comment]
Hmm! Maybe they're finally on to me. For the time being, for my slack instance, the <instance>.slack.com/customize endpoint has a `TS.boot_data.api_token`, so I'll update the snippet to reflect that. Hopefully that page doesn't change soon!

> It's easy! Open any signed in slack window, e.g. subdomain.slack.com/customize, right click anywhere > inspect element. Open the console and paste:
    ```window.prompt("your api token is: ", TS.boot_data.api_token)```

**Comment by curtisgibby** [comment]
Yep, I was just coming to the same conclusion. Looks like the user-logged-in page now has `xoxc`-level tokens, which do work for changing a user's status, but not for updating emoji.

**Comment by jackellenberger** [comment]
Very interesting, I haven't seen those documented anywhere.

I'm going to hold up on committing the change to the readme until this feature rollout is complete. Thanks for the report!

**Comment by curtisgibby** [comment]
In the console:

```
window.slackDebug.localConfig.getLocalConfigForTeamByKey(
    window.slackDebug.localConfig.getLocalConfigByKey('lastActiveTeamId'),
    'token'
);
```

**Comment by anindha** [comment]
@curtisgibby out of interest, how did you figure this out?

**Comment by curtisgibby** [comment]
Just digging around in the console on that "customize" page.
