### ISSUE TITLE
Handling users with "/" in their username

### ISSUE THREAD

**Issue by MattyGroch** [jackellenberger/emojme#59]
I just tried using this for the first time but I can't actually run a `user-stats` because one of the users has "/" in their Slack user name which breaks since filenames cant contain "/". Building the .json for that user in ./build/ is impossible.

**Comment by jackellenberger** [comment]
yeahhh our instance has some users with emoji in their names too so i've been meaning to fix this. Hopefully i'll have some time this weekend unless you want to submit a PR!

**Comment by jackellenberger** [comment]
Just published https://www.npmjs.com/package/emojme/v/1.9.1 let me know if that doesn't help!

**Comment by MattyGroch** [comment]
I noticed after I reached out that you already had a mechanism for replacing spaces (safeUserName) so I added a forward slash to that function buy you beat me to the PR. Thanks for the help!
