### ISSUE TITLE
Finding User Token

### ISSUE THREAD

**Issue by JohnRoux** [jackellenberger/emojme#65]
It seems like the guide over here is outdated: https://github.com/jackellenberger/emojme/tree/1.9.0#finding-a-slack-token

I can't seem to generate a working user token at all.

The Slack For Web section no longer works, it's only responding with "client" tokens (xoxc)

And the slack for Desktop isn't working for me either, I can't get the devTools to show up no matter how many ways or devices I've tested on

Any idea as to where else I could get a working user-token?

**Comment by jackellenberger** [comment]
Ach! Sorry for leaving this for so long! Something something GitHub notifications. I'll update the instructions, the token is now a cookie token and you need the cookie contents too, take a look at the recently closed bugs (or i think the changelog) for a bit more info.
