### ISSUE TITLE
Use your splendid token/cookie instructions

### ISSUE THREAD

**Issue by rusq** [jackellenberger/emojme#66]
Hey @jackellenberger , I'm astonished how easy you made it for the users to get the slack token/cookie with the extension.

I have a similar problem in [Slackdump](https://github.com/rusq/slackdump) - i think it's might be complex for the unprepared person to do all this magic with going into the dev console, finding the token, and cookie, copy pasting, putting into a file.

Would you mind if I reference your extension and provide the instructions in the readme file for slackdump project?
Along the lines of:
"If you happen to have _THIS EXTENSION_, you can easily export your ... "

Cheers

**Comment by jackellenberger** [comment]
Hey, I don't mind at all! Go for it!

**Comment by rusq** [comment]
Thank you!
