### ISSUE TITLE
[FEATURE REQUEST] - Support Uploading directories

### ISSUE THREAD

**Issue by matthew-gerstman** [jackellenberger/emojme#69]
It would be really nice if I could just upload all emoji in a directory without having to build a list in advance.

**Comment by jackellenberger** [comment]
Nice, yeah, this sure would be nice to support natively, and I don't think it would be all too difficult to implement.

there are two allowed input formats currently, [adminList json's](https://jackellenberger.github.io/emojme/module-upload.html#~jsonEmojiListFormat), and [emojipacks yaml's](https://jackellenberger.github.io/emojme/module-upload.html#~yamlEmojiListFormat). Yaml's would probably be easier in this case, but i don't have `yq` installed so i'm not gonna try it. The key is [here](https://github.com/jackellenberger/emojme/blob/f52ce271fc2a598cc14a106538fe2b8b3b6d37bc/lib/emoji-add.js#L78), we accept either a url or a src file path, so all you need to do if you don't want to write native support is to `ls` your directory of emoji and pipe that to a json/yaml of <file name : file path>. Something like:

```sh
npx emojme upload --auth-json $AUTH --src <(ls | jq magic)
```

I'll come back later and see if I can't actually work out what that jq magic is.

**Comment by matthew-gerstman** [comment]
ooh thank you so much. We could also just write a script that takes the folder and generates the appropriate json/yaml

**Comment by jackellenberger** [comment]
Oh hey wait! I know why this seemed like such a good idea and why i knew a shortcut answer that made me not want to write any code for it! I already asked this question and worked out the jq magic!

https://github.com/jackellenberger/emojme/issues/54

**Comment by matthew-gerstman** [comment]
ooh thank you! that generated a well formed json file. I'm running into this error now

```/Users/matthew/src/emojme/lib/util/file-utils.js:86
    throw new Error('Emoji Url does not contain acceptable data');
          ^

Error: Emoji Url does not contain acceptable data
    at Object.getData (/Users/matthew/src/emojme/lib/util/file-utils.js:86:11)
    at Function.createMultipart (/Users/matthew/src/emojme/lib/emoji-add.js:78:39)
    at EmojiAdd.uploadSingle (/Users/matthew/src/emojme/lib/emoji-add.js:24:42)
    at /Users/matthew/src/emojme/lib/emoji-add.js:54:35
    at Array.map (<anonymous>)
    at EmojiAdd.upload (/Users/matthew/src/emojme/lib/emoji-add.js:54:17)
    at /Users/matthew/src/emojme/emojme-upload.js:160:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async upload (/Users/matthew/src/emojme/emojme-upload.js:164:36)

matthew at Matthews-iMac-272 in ~/src/emojme on master!
```

any suggestions?

**Comment by matthew-gerstman** [comment]
I had to add .txt as an extension. Github won't let you upload json directly.

[emoji.json.txt](https://github.com/jackellenberger/emojme/files/8894313/emoji.json.txt)

**Comment by matthew-gerstman** [comment]
It seems to make it to zune.png and then error out

```{ path: 'directory/zombie1.jpg' }
{ path: 'directory/zombo.png' }
{ path: 'directory/zoodle.jpg' }
{ path: 'directory/zoom-cat.png' }
{ path: 'directory/zoom-logo.png' }
{ path: 'directory/zoom.png' }
{ path: 'directory/zoomcall.png' }
{ path: 'directory/zulip.png' }
{ path: 'directory/zune.png' }
/Users/matthew/src/emojme/lib/util/file-utils.js:89
    throw new Error("Emoji Url does not contain acceptable data");
          ^
```

**Comment by matthew-gerstman** [comment]
aaah there are subdirectories that got converted in the script, thats the problem

**Comment by matthew-gerstman** [comment]
It's working now!! Thank you!

**Comment by jackellenberger** [comment]
If you've got a nice working command for posterity, plop it in here

**Comment by matthew-gerstman** [comment]
I'll do you one better https://github.com/jackellenberger/emojme/pull/70

**Comment by jackellenberger** [comment]
:shipit: closing this, keeping #54 open
