### ISSUE TITLE
Upload with YAML file

### ISSUE THREAD

**Issue by rreynier** [jackellenberger/emojme#9]
Many emoji packs seem to support YAML files only.  It appears that this tool only works with JSON data.  Is uploading with YAML supported somehow?  Ex: https://github.com/jmhobbs/cultofthepartyparrot.com

**Comment by jackellenberger** [comment]
It could be made to work! I'll take a look into it.

**Comment by jackellenberger** [comment]
@rreynier let me know how this branch works for ya: https://github.com/jackellenberger/emojme/tree/support-yaml-uploads

**Comment by jackellenberger** [comment]
I'm just yolo'ing this in cause it also resolves some self inflicted issues. Let me know if you have any trouble!
